---
PRINT_ALPACA: false
EMAIL_REPORTER: false
APPLY_FIXES: all

# Lint specifig settings
ENABLE_LINTERS:
  [
    BASH_SHELLCHECK,
    COPYPASTE,
    REPOSITORY_GITLEAKS,
    REPOSITORY_SECRETLINT,
    MARKDOWN_MARKDOWN_LINT,
    YAML_PRETTIER,
  ]

COPYPASTE_JSCPD_ARGUMENTS: --ignore "**/report/**","LICENSES" --threshold "10"
